export const data = [
  {
    id: 1,
    title: "Adidas black t-shirt lorem ipsum dolor sit amet",
    img: "/images/Group 575.png",
    price: 9.999,
    oldPrice: 12.99,
    description: "Adidas black t-shirt lorem ipsum dolor sit amet",
    rating: 4.9,
    imgs: [
      "/images/Group 333.png",
      "/images/Group 331.png",
      "/images/Group 332.png",
      "/images/Group 334.png",
      "/images/Group 335.png",
    ],
  },
  {
    id: 2,
    title: "Nike white sneakers lorem ipsum dolor sit",
    img: "/images/Group 583.png",
    price: 7.499,
    oldPrice: 9.99,
    description: "Nike white sneakers lorem ipsum dolor sit amet",
    rating: 4.7,
    imgs: [
      "/images/Group 336.png",
      "/images/Group 337.png",
      "/images/Group 338.png",
      "/images/Group 339.png",
      "/images/Group 340.png",
    ],
  },
  {
    id: 3,
    title: "Puma red shorts lorem ipsum dolor sit amet",
    img: "/images/Group 589.png",
    price: 5.999,
    oldPrice: 7.99,
    description: "Puma red shorts lorem ipsum dolor sit amet",
    rating: 4.5,
    imgs: [
      "/images/Group 341.png",
      "/images/Group 342.png",
      "/images/Group 343.png",
      "/images/Group 344.png",
      "/images/Group 345.png",
    ],
  },
  {
    id: 4,
    title: "Reebok blue cap lorem ipsum dolor sit amet",
    img: "/images/Group 597.png",
    price: 3.499,
    oldPrice: 4.99,
    description: "Reebok blue cap lorem ipsum dolor sit amet",
    rating: 4.3,
    imgs: [
      "/images/Group 346.png",
      "/images/Group 347.png",
      "/images/Group 348.png",
      "/images/Group 349.png",
      "/images/Group 350.png",
    ],
  },
];
